env:
    global:
        - CC_TEST_REPORTER_ID=787a2f89b15c637323c7340d65ec17e898ac44480706b4b4122ea040c2a88f1d

language: node_js

node_js:
    - "node"
    - "8"
    - "7"

sudo: false

git:
    submodules: false

before_script:
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
    - chmod +x ./cc-test-reporter
    - ./cc-test-reporter before-build

script:
    - make install test

after_script:
    - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

after_success:
    - npm run report-coveralls
    - npm run report-codecov

notifications:
    email: false
